# Generated by Django 4.2.6 on 2023-10-19 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_api', '0003_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.CharField(choices=[('PB', 'Paperback'), ('EB', 'E-book')], default='HC', max_length=20)),
                ('authors', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='sbookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_api.student_book'),
        ),
        migrations.DeleteModel(
            name='Students_book',
        ),
    ]
